### ISSUE TITLE
Error: Cannot find module 'debug/node'

### ISSUE THREAD

**Issue by Lellansin** [visionmedia/debug#390]
```javascript
Error: Cannot find module 'debug/node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/fe.game_admin/node_modules/babel-core/lib/transformation/file/logger.js:9:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I'm not sure what happened, but it just appear suddenly, should I paste more info?

**Comment by Lellansin** [comment]
duplicate with https://github.com/visionmedia/debug/issues/389
