### ISSUE TITLE
internal/modules/cjs/loader.js 969 throw err

### ISSUE THREAD

**Issue by gobend** [visionmedia/debug#763]
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- G:\movieapp\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (G:\movieapp\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'G:\\movieapp\\index.js' ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Qix-** [comment]
Has nothing to do with this package.
